app = "my-napcat"
primary_region = "sin"

[env]
  ACCOUNT = "1215207734"
  WEBUI_TOKEN = "Base64@d3p4"
  MODE = "ws"
  TEST_MODE = "1"

[http_service]
  internal_port = 6099
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

[vm]
  size = "shared-cpu-1x"
  memory = "768mb"

[[mounts]]
  source = "napcat_data"
  destination = "/data"
