app = "my-napcat"
primary_region = "sin"

[env]
  ACCOUNT = "3059754914"
  WEBUI_TOKEN = "Base64@d3p4"

[http_service]
  internal_port = 6099
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["tls", "http"]
  port = 3001

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"

[[mounts]]
  source = "napcat_data"
  destination = "/data"
